
-- CHECKS DUE TO BUGS FROM PREVIOUS VERSIONS
DELETE FROM TDISTRIBUTION_LOG WHERE DISTRIBUTION_ID IN
(
SELECT ID FROM TDISTRIBUTION WHERE RPT_TYPE=0 AND RPT_ID NOT IN (SELECT ID FROM T_OLAP_REPORTS)
UNION
SELECT ID FROM TDISTRIBUTION  WHERE RPT_TYPE=1 AND RPT_ID NOT IN (SELECT ID FROM T_STORECHECK_REPORTS)
UNION
SELECT ID FROM TDISTRIBUTION  WHERE RPT_TYPE=2 AND RPT_ID NOT IN (SELECT ID FROM T_SQL_REPORTS)
UNION
SELECT ID FROM TDISTRIBUTION  WHERE RPT_TYPE=3 AND RPT_ID NOT IN (SELECT ID FROM T_MDX_REPORTS)
)
GO

DELETE FROM TDISTRIBUTION WHERE RPT_TYPE=0 AND RPT_ID NOT IN (SELECT ID FROM T_OLAP_REPORTS)
GO
DELETE FROM TDISTRIBUTION WHERE RPT_TYPE=1 AND RPT_ID NOT IN (SELECT ID FROM T_STORECHECK_REPORTS)
GO
DELETE FROM TDISTRIBUTION WHERE RPT_TYPE=2 AND RPT_ID NOT IN (SELECT ID FROM T_SQL_REPORTS)
GO
DELETE FROM TDISTRIBUTION WHERE RPT_TYPE=3 AND RPT_ID NOT IN (SELECT ID FROM T_MDX_REPORTS)
GO