//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace FI.UI.ConsoleClient.PingService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PingServiceSoap", Namespace="http://tempuri.org/")]
    public class PingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public PingService() {
            this.Url = "http://localhost/FieldInformer.NET/WebServices/PingService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PingOlapSystem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PingOlapSystem(string Mdx, string MailTo) {
            this.Invoke("PingOlapSystem", new object[] {
                        Mdx,
                        MailTo});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPingOlapSystem(string Mdx, string MailTo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PingOlapSystem", new object[] {
                        Mdx,
                        MailTo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPingOlapSystem(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
