//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace FI.UI.ConsoleClient.DistributionService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DistributionServiceSoap", Namespace="http://tempuri.org/")]
    public class DistributionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DistributionService() {
            this.Url = "http://localhost/FieldInformer.NET/UI.Web/WebServices/DistributionService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AsyncSendQueuedDistributions", RequestNamespace="http://tempuri.org/", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AsyncSendQueuedDistributions(string CompanyNameShort) {
            this.Invoke("AsyncSendQueuedDistributions", new object[] {
                        CompanyNameShort});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAsyncSendQueuedDistributions(string CompanyNameShort, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AsyncSendQueuedDistributions", new object[] {
                        CompanyNameShort}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAsyncSendQueuedDistributions(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnqueueScheduledDistributions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnqueueScheduledDistributions(string CompanyNameShort) {
            this.Invoke("EnqueueScheduledDistributions", new object[] {
                        CompanyNameShort});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnqueueScheduledDistributions(string CompanyNameShort, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnqueueScheduledDistributions", new object[] {
                        CompanyNameShort}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndEnqueueScheduledDistributions(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnqueueScheduledDistributionsWDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnqueueScheduledDistributionsWDate(string CompanyNameShort, System.DateTime Date) {
            this.Invoke("EnqueueScheduledDistributionsWDate", new object[] {
                        CompanyNameShort,
                        Date});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnqueueScheduledDistributionsWDate(string CompanyNameShort, System.DateTime Date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnqueueScheduledDistributionsWDate", new object[] {
                        CompanyNameShort,
                        Date}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndEnqueueScheduledDistributionsWDate(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
